// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9xoHI79QJNidLJ416IzLhPZHYY2812y4',
    appId: '1:498084647772:web:a7fd34a1d1d726fe1be799',
    messagingSenderId: '498084647772',
    projectId: 'resq-b5952',
    authDomain: 'resq-b5952.firebaseapp.com',
    storageBucket: 'resq-b5952.firebasestorage.app',
    measurementId: 'G-PM27ZC6DL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSNjB1S7M38-WuqaqMAFyOZxLgagJHiEk',
    appId: '1:498084647772:android:94ee1d2cf1025b571be799',
    messagingSenderId: '498084647772',
    projectId: 'resq-b5952',
    storageBucket: 'resq-b5952.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNsmDG3xZIAcUFTIXZ0U-JgUe6mGzduQU',
    appId: '1:498084647772:ios:0812a221a0bb0da11be799',
    messagingSenderId: '498084647772',
    projectId: 'resq-b5952',
    storageBucket: 'resq-b5952.firebasestorage.app',
    iosBundleId: 'com.resq.resq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNsmDG3xZIAcUFTIXZ0U-JgUe6mGzduQU',
    appId: '1:498084647772:ios:0812a221a0bb0da11be799',
    messagingSenderId: '498084647772',
    projectId: 'resq-b5952',
    storageBucket: 'resq-b5952.firebasestorage.app',
    iosBundleId: 'com.resq.resq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9xoHI79QJNidLJ416IzLhPZHYY2812y4',
    appId: '1:498084647772:web:6aae110f82bb79261be799',
    messagingSenderId: '498084647772',
    projectId: 'resq-b5952',
    authDomain: 'resq-b5952.firebaseapp.com',
    storageBucket: 'resq-b5952.firebasestorage.app',
    measurementId: 'G-QYZJ493WYT',
  );
}
